### ISSUE TITLE
Produce a warning message in case the `frame_attribute` specified, is unavailable on the nodes

### ISSUE THREAD

**Issue by lmanan** [funkelab/motile#92] opened 2024-04-12 19:42 UTC
While initializing a `TrackGraph` object, 

```python
from motile import TrackGraph
track_graph = TrackGraph(nx_graph = candidate_graph)
```
I had forgotten to explicitly specify the `frame_attribute`, which caused the `is_hyperedge_nx_node` method [here](https://github.com/funkelab/motile/blob/5415cd4b48b28a830cff7df1485fd6d38877ee7a/motile/track_graph.py#L108) to evaluate to `True`, producing an object with no edges.

Maybe a warning message can be printed whenever the `self.frame_attribute` is not found on the nodes, in order to trouble shoot and distinguish the hyper-edge scenario from just specifying the wrong `frame_attribute` while initializing the object.

**Comment by funkey** [comment] 2024-04-12 20:28
Duplicate of #91

**Closed by funkey** 2024-04-12 20:28 UTC
Labels: enhancement
